// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using festekelado_main.Models;

#nullable disable

namespace festekelado_main.Migrations
{
    [DbContext(typeof(FestekContext))]
    partial class FestekContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("festekelado_main.Models.Futarok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nev");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("futarok", (string)null);
                });

            modelBuilder.Entity("festekelado_main.Models.Rendelesek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Címzett")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("címzett");

                    b.Property<int?>("Futarid")
                        .HasColumnType("int(11)")
                        .HasColumnName("futarid");

                    b.Property<int>("Rendeltdb")
                        .HasColumnType("int(11)")
                        .HasColumnName("rendeltdb");

                    b.Property<int?>("Szinid")
                        .HasColumnType("int(11)")
                        .HasColumnName("szinid");

                    b.Property<int>("osszar")
                        .HasColumnType("int(11)")
                        .HasColumnName("osszar");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Futarid" }, "futarid");

                    b.HasIndex(new[] { "Szinid" }, "szinid");

                    b.ToTable("rendelesek", (string)null);
                });

            modelBuilder.Entity("festekelado_main.Models.Szinek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("Db")
                        .HasColumnType("int(11)")
                        .HasColumnName("db");

                    b.Property<string>("Szin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("szin");

                    b.Property<int>("ar")
                        .HasColumnType("int(11)")
                        .HasColumnName("ar");

                    b.Property<string>("kepurl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("kepurl");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("szinek", (string)null);
                });

            modelBuilder.Entity("festekelado_main.Models.Rendelesek", b =>
                {
                    b.HasOne("festekelado_main.Models.Futarok", "Futar")
                        .WithMany("Rendeleseks")
                        .HasForeignKey("Futarid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("rendelesek_ibfk_1");

                    b.HasOne("festekelado_main.Models.Szinek", "Szin")
                        .WithMany("Rendeleseks")
                        .HasForeignKey("Szinid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("rendelesek_ibfk_2");

                    b.Navigation("Futar");

                    b.Navigation("Szin");
                });

            modelBuilder.Entity("festekelado_main.Models.Futarok", b =>
                {
                    b.Navigation("Rendeleseks");
                });

            modelBuilder.Entity("festekelado_main.Models.Szinek", b =>
                {
                    b.Navigation("Rendeleseks");
                });
#pragma warning restore 612, 618
        }
    }
}
